- hosts: master
  become: yes
  tasks:
  - name: remove swap
    shell: "swapoff -a"
 
  - name: initialize the cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
    args:
      chdir: $HOME
      creates: cluster_initialized.txt
 
  - name: create .kube directory
    become: yes
    become_user: sherif
    file:
      path: $HOME/.kube
      state: directory
      mode: 0755
 
  - name: copy admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/sherif/.kube/config
      remote_src: yes
      owner: sherif
 
  - name: install Pod network
    become: yes
    become_user: sherif
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
    args:
      chdir: $HOME
      creates: pod_network_setup.txt
