- hosts: master
  become: yes
  gather_facts: false
  tasks:
  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command
 
  - name: Copy join command to local file
    become: yes
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
 
- hosts: workers
  become: yes
  tasks:
  - name: remove swap
    shell: "swapoff -a"
 
  - name: join cluster	
    copy: src=join-command dest=/tmp/join-command.sh mode=0777
  - name: Join the node to cluster
    command: sh /tmp/join-command.sh
